title: Ipse Dixit
description: A Personal Blog
paginate: 5 

abackground_image:          /assets/image/background.jpg

nav:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About Me
    url: /about/
  
